routes:
  /about/: about
  /services/: services
  /blog/: blog
  /winter-places/: winter
  /secret-winter/: secret-winter

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
